tailwind.config.js
Update tailwind.config.js with new color palette additions
=> refactor: Update tailwind.config.js with new color palette additions

package-lock.json, src/components/auth/LoginForm.jsx, src/components/auth/RegisterForm.jsx, src/pages/Login.jsx, src/pages/Register.jsx, src/router/AppRouter.jsx
feat: Added Login and Register pages, updated AppRouter to include routes for these pages
=> Login-Register

src/components/Blog/BlogDetail.jsx, src/helper/blogs.json
feat; blogdetails page completed and back button added
=> Soul-journey/erkan

src/App.jsx, src/components/auth/LoginForm.jsx, src/components/auth/LoginHeader.jsx, src/components/auth/RegisterHeader.jsx, src/features/authSlice.jsx, src/hooks/useAxios.jsx, src/index.css, src/pages/Login.jsx, src/pages/Register.jsx
Update codes in various pages and created useAxios hook
=> Soul-journey/gokce

package-lock.json, src/components/home/FAQ.jsx, src/components/home/Quiz.jsx, src/helper/quizData.json, src/index.css, src/pages/Home.jsx
Feat: updated FAQ component and added quiz component
=> Feat: updated FAQ component and added quiz component

src/components/auth/LoginForm.jsx, src/components/auth/RegisterForm.jsx, src/pages/Login.jsx, src/pages/Register.jsx
Login-Register functionality added
=> Soul-journey/gokce: Login-Register

src/components/auth/LoginForm.jsx, src/hooks/useAuthCall.jsx, src/pages/Login.jsx
* Finalized the designs for Login and Register pages.
* Implemented functionality for user Login, Register, and Logout.
* Enabled Google authentication for Login and Register.
* Ensured seamless integration between UI and authentication processes.
=> Complete Login & Register Page Designs with Authentication Features

src/components/auth/LoginForm.jsx, src/components/auth/LoginHeader.jsx, src/components/auth/RegisterHeader.jsx, src/hooks/useAuthCall.jsx, src/pages/Login.jsx, src/pages/Register.jsx, src/styles/globalStyle.js
Added forgot password button to Login page
=> Soul-journey/gokce: About forgot Password

src/hooks/useAuthCall.jsx, src/pages/Login.jsx, src/pages/Register.jsx, src/styles/globalStyle.js
refactor: update login and register pages to add hover underline effect to links
=>  login and register pages

package-lock.json
refactor : package-lock.json updated
=> refactor : package-lock.json updated

src/components/pricing/PricingForm.jsx
=> refactor:Pricing Page

src/components/home/FAQ.jsx
update: Refactor FAQ component
=> Soul-journey/mustafa

src/components/Sidebar.jsx, src/pages/Account.jsx, src/pages/Chat.jsx, src/pages/Dashboard.jsx, src/pages/VideoCall.jsx, src/pages/WriteBlog.jsx, src/router/AppRouter.jsx, tailwind.config.js
feat: Added new routes and components to AppRouter for profile page and updated Tailwind config
=> AppRouter and Profile page

src/components/auth/LoginForm.jsx, src/components/auth/RegisterForm.jsx
feat: Added onClick event to submit buttons in LoginForm and RegisterForm components
=> onClick event for LoginForm and RegisterForm

src/components/pricing/PricingForm.jsx, src/components/pricing/PricingHeader.jsx, src/pages/Pricing.jsx
Add new arrangements to the Pricing Page.
=> feat:Add new arrangements to the Pricing Page.

src/components/LanguageSelector.jsx, src/components/Navbar.jsx
refactor: LanguageSelector component to use select dropdown instead of buttons
=> refactor: LanguageSelector component to use select dropdown instead of buttons

src/components/LanguageSelector.jsx
Update: LanguageSelector.jsx to use onChange event instead of onClick on select options
=> Update: LanguageSelector.jsx to use onChange event instead of onClick on select options

src/components/Sidebar.jsx, src/components/sidebar/SidebarListItems.jsx
Updated the styles and the functionality of sidebar and items
=> Soul-journey/gokce: Sidebar

src/components/home/FAQ.jsx, src/locales/de.json, src/locales/en.json
refactor: Updated FAQ translations in en.json and de.json files and modified FAQ text in FAQ.jsx component
=> refactor: Updated FAQ translations in en.json and de.json files and modified FAQ text in FAQ.jsx component

src/App.jsx, src/components/Sidebar.jsx, src/components/auth/AccountForm.jsx, src/pages/Account.jsx
Added form to update user account
=> Soul-journey/gokce: Accout-AccoutFrom

src/components/button/Button.jsx, src/router/PrivateRouter.jsx
=> feat: Add Private Router

src/pages/Account.jsx
=> Soul-journey/gokce: Account Page

src/index.css, src/pages/Account.jsx
refactor: Update index.css button styles to use new .account-btn class
=> tailwind Configuration

package-lock.json, package.json, src/components/pricing/PricingForm.jsx
=> feat:Add Stripe for Frontend

src/components/button/Button.jsx, src/components/pricing/PricingForm.jsx, src/pages/Pricing.jsx
Managed Pricing Page's padding and buttons.
=> refactor: Managed Pricing Page's padding and buttons.

package-lock.json, src/components/team/TeamDetail.jsx
=> Soul-journey/gokce: TeamDetail

src/pages/Home.jsx
Integrate the HeroSection component into the Home page layout.
=> Add HeroSection component to Home page

src/components/adminPanel/AppointmentForm.jsx, src/components/adminPanel/AppointmentRow.jsx, src/components/adminPanel/BlogRow.jsx, src/components/adminPanel/CategoryForm.jsx, src/components/adminPanel/CategoryRow.jsx, src/components/adminPanel/ListToolBar.jsx, src/components/appointment/AppointmentDetails.jsx, src/features/appointmentSlice.jsx, src/features/categorySlice.jsx, src/helper/dateFormatter.js, src/hooks/useBlogCall.jsx, src/hooks/useCategoryCall.jsx, src/hooks/usePaginationCall.jsx, src/pages/AppointmentManagement.jsx, src/pages/BlogManagement.jsx, src/pages/CategoryManagement.jsx, src/pages/UserManagement.jsx
Introduce new functionalities for category management, including creation, deletion, and updates. Enhance appointment management with modal support and improved error handling. Implement pagination and search capabilities for blog management. Refactor components for better performance and maintainability.
=> Enhance category and appointment management features

package-lock.json, package.json, src/components/auth/AccountChangePasswordForm.jsx, src/components/auth/AccountDelete.jsx, src/components/auth/AccountForm.jsx, src/components/auth/AccountUploadProfilePicture.jsx, src/components/auth/RegisterHeader.jsx, src/features/userSlice.jsx, src/helper/ToastNotify.js, src/hooks/useUserCall.jsx, src/index.css, src/pages/Account.jsx, src/styles/globalStyle.js
=> Soul-journey/gokce: Account

index.html, package-lock.json, package.json, src/components/Navbar.jsx, src/components/chat/LeftSidebar.jsx, src/components/chat/MainChatArea.jsx, src/components/dashboard/UserCard.jsx, src/context/SocketContext.jsx, src/features/chatSlice.jsx, src/hooks/useChatCall.jsx, src/main.jsx, src/pages/Chat.jsx
updated packege.json , thus neccesery npm i
=> Soul journey/ayse

package-lock.json, src/components/adminPanel/Pagination.jsx, src/components/team/TeamDetail.jsx, src/components/team/TeamDetailFeedbackCards.jsx, src/components/team/TeamDetailFeedbackCardsModal.jsx, src/helper/dateFormatter.js
=> Soul-journey/gokce TeamDetailFeedback

src/components/team/TeamDetail.jsx, src/components/team/TeamDetailBody.jsx
feat: Added sticky tab navigation and scrolling functionality to TeamDetail component
=> tab navigation TeamDetail component

src/components/Navbar.jsx, src/components/team/TeamDetail.jsx, src/components/team/TeamDetailBody.jsx, src/components/team/TeamDetailFeedbackCards.jsx, src/components/team/TeamDetailHeader.jsx
=> Soul-journey/gokce: Navbar and TeamDetail

package-lock.json
=> refactor:package-lock.json

src/components/Blog/BlogDetail.jsx, src/components/Blog/BlogHeroSection.jsx, src/components/Blog/BlogList.jsx, src/components/Card.jsx, src/components/Contact/ContactForm.jsx, src/components/Contact/ContactHeader.jsx, src/components/Contact/ContactInfo.jsx, src/components/Footer.jsx, src/components/appointment/DashboardCalendar.jsx, src/components/auth/AccountTherapistForm.jsx, src/components/auth/LoginHeader.jsx, src/components/auth/RegisterHeader.jsx, src/components/chat/LeftSidebar.jsx, src/components/home/BlogsSection.jsx, src/components/home/FAQ.jsx, src/components/home/ProcessSection.jsx, src/components/sidebar/SidebarListItems.jsx, src/components/team/Join.jsx, src/components/team/TeamCard.jsx, src/features/therapistSlice.jsx, src/hooks/useAuthCall.jsx, src/hooks/useTherapistCall.jsx, src/pages/Account.jsx, src/pages/Blog.jsx, src/pages/Contact.jsx, src/pages/Home.jsx, src/pages/Login.jsx, src/pages/Register.jsx, src/pages/Team.jsx
Dark Mode added several pages. Started to fix account page for therapist
=> Soul-journey/gokce Dark mode and Account

src/components/home/FAQ.jsx
Refactor FAQ component: remove unused text and adjust image size
=> Refactor FAQ component: remove unused text and adjust image size

src/hooks/useTherapistCall.jsx, src/hooks/useUserCall.jsx, src/router/PrivateRouter.jsx
refactor: Update logout and navigation logic in useTherapistCall, useUserCall, and PrivateRouter components
=> Private Router

src/components/home/Quiz.jsx, src/components/pricing/PricingForm.jsx
Updated Quiz button and PricingForm to use translated strings
=> Updated Quiz button and PricingForm to use translated strings

src/components/adminPanel/Pagination.jsx, src/features/blogSlice.jsx, src/features/paginationSlice.jsx, src/hooks/useBlogCall.jsx, src/hooks/usePaginationCall.jsx, src/pages/Blog.jsx
Introduce search capabilities for blogs, update the blog slice to manage filtered results, and enhance pagination API calls to support query parameters. Refactor the Blog component to utilize the new filtered blogs and search term state.
=> Add search and filter functionality to blog section

src/components/Blog/BlogDetail.jsx, src/components/adminPanel/Pagination.jsx, src/components/team/TeamCard.jsx, src/components/team/TeamDetail.jsx, src/components/team/TeamDetailBody.jsx, src/components/team/TeamDetailFeedbackCards.jsx, src/features/therapistSlice.jsx, src/hooks/useTherapistCall.jsx, src/pages/Team.jsx
=> Soul-journey/gokce Team Detail Pagination

src/components/team/TeamCard.jsx, src/pages/Team.jsx
refactor : Removed unused code and updated TeamCard and Team pages to reflect changes
=>  TeamCard and Team pages 

src/components/pricing/PricingForm.jsx, src/components/pricing/PricingHeader.jsx, src/pages/Pricing.jsx
Pricing.jsx, PricingHeader.jsx and PricingForm.jsx were renovated.
=> refactor: Pricing.jsx, PricingHeader.jsx and PricingForm.jsx were renovated.

src/components/pricing/PricingForm.jsx
Update PricingForm.jsx to use environment variables for Stripe API key and base URL
=> feat:Update PricingForm.jsx to use environment variables for Stripe API key and base URL

src/components/adminPanel/TherapistForm.jsx, src/components/adminPanel/UserRow.jsx, src/components/pricing/PricingForm.jsx, src/features/therapistSlice.jsx
Added new fields to TherapistForm, logged user in UserRow, and adjusted grid spacing in PricingForm
=> feat:Added new fields to TherapistForm, logged user in UserRow, and adjusted grid spacing in PricingForm

src/components/pricing/PricingForm.jsx
Add Language arrangement on Stripe
=> feat:Add Language arrangement on Stripe

src/components/CookieConsent.jsx, src/components/Sidebar.jsx, src/components/auth/AccountTherapistForm.jsx, src/components/chat/LeftSidebar.jsx, src/components/chat/MainChatArea.jsx, src/components/chat/RightSidebar.jsx, src/components/dashboard/NotesModal.jsx, src/components/dashboard/UserCard.jsx, src/components/home/Card.jsx, src/components/sidebar/SidebarListItems.jsx, src/hooks/useNotificationCall.jsx, src/hooks/useTherapistCall.jsx, src/locales/de.json, src/locales/en.json, src/locales/tr.json, src/pages/AuthFail.jsx, src/pages/AuthSuccess.jsx, src/pages/PrivacyPolicy.jsx, src/pages/TermsAndConditions.jsx
=> Soul-journey/gokce: Language

src/pages/BlogDetail.jsx, src/router/AppRouter.jsx
refactor? Removed BlogDetail component from components/blog directory and moved it to pages/BlogDetail
=>  BlogDetail 

src/components/team/TeamDetail.jsx
reafctor: Update import path for AppointmentCalendar component
=> AppointmentCalendar 

src/components/team/TeamDetailFeedbackCardsModal.jsx
feat: Added translation parameter to getTimeAgo function call in TeamDetailFeedbackCardsModal component
=> getTimeAgo 

vercel.json
Introduce a configuration file for Vercel to manage URL rewrites and enable deployment settings for the main branch.
=> Add Vercel configuration for rewrites and deployment settings

src/components/About/AboutHeroSection.jsx, src/components/ServicesPage/ServicesHeroSection.jsx, src/components/blog/BlogHeroSection.jsx, src/components/dashboard/Notes.jsx, src/components/dashboard/PatientList.jsx, src/components/dashboard/UserCard.jsx, src/components/pricing/PricingHeader.jsx, src/components/team/HeroSection.jsx
Enhance the styling and structure of various components to ensure better responsiveness, readability, and visual appeal across the application. Adjustments include updates to padding, layout, and text visibility in sections such as Blog, Pricing, About, Services, and UserCard. Additionally, improve user data access for safety and clarity.
=> Refactor components for improved responsiveness and readability

index.html, src/components/Navbar.jsx
Replace the favicon with a new image and improve null checks for user data in the Navbar component to prevent potential errors.
=> Update favicon and enhance null checks in Navbar component

index.html, public/robots.txt, src/router/AppRouter.jsx, vite.config.js
Add meta tags and a robots.txt file for better SEO optimization. Implement lazy loading for routes to enhance performance and user experience.
=> Enhance SEO and improve route loading performance

src/pages/BlogDetail.jsx
refactor: Update handleLike function to use translated likeLoginWarning message
=> likeLoginWarning 

src/features/blogSlice.jsx
refactor: Update blogSlice initialState to set singleBlog to null
=> blogSlice 
